---
development:
  :queues:
    - [critical,4]
    - [default, 2]
    - [low]

:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - default
  - critical
  - low
